### ISSUE TITLE
MOSFETs Q1-3

### ISSUE THREAD

**Issue by bot1131357** [devttys0/IRis#1]
Hi there,

This is really more of an enquiry. Could you tell me what the three MOSFETs (MMBF4117) are doing in the circuit? As far as I can tell, they seem redundant to me. 

Thanks!

**Comment by devttys0** [comment]
Those are actually JFETs which are connected as diodes in the circuit. Their purpose is to prevent opamp U1 from saturating if its output voltage exceeds the voltage drop of the three PN junctions.

JFETs were originally chosen here to prevent reverse leakage, as they have very low-leakage properties compared with a typical silicon diode. However, in the final circuit there should never be a situation where they are reverse biased, so reverse leakage current really isn't a concern, and the JFETs can easily be replaced with a run-of-the-mill diode.
