### ISSUE TITLE
5V and GND shorted

### ISSUE THREAD

**Issue by bot1131357** [devttys0/IRis#2]
Hi again,

I am experiencing some difficulties assembling the board. Somehow my +5V pad is shorted to GND. 
 
When I look at the PCB editor, it shows that the B.Cu layer is connected to the +5V pad, but it also seemed to be connected to the circled GND pad.  

![capture2](https://user-images.githubusercontent.com/18155369/34195686-f6828f52-e5b2-11e7-9a49-95d10fc7172b.PNG)

(Also, would you be able to include in the documentation the correct output signal when the board is working?)

**Comment by devttys0** [comment]
The top copper layer (which your circled ground pad is connected to) should be ground, and the bottom copper layer (which the +5V pad should be connected to) is Vcc.

Here is my view in KiCAD:

<img width="553" alt="screen shot 2018-01-15 at 7 57 09 pm" src="https://user-images.githubusercontent.com/5703146/34967121-6ca37630-fa2e-11e7-9e77-3b6d71c890ba.png">

When viewed in 3D mode, it should be clear that the 5V pad is not connected to the top copper layer (ground):

<img width="683" alt="screen shot 2018-01-15 at 7 57 25 pm" src="https://user-images.githubusercontent.com/5703146/34967135-807a6cae-fa2e-11e7-962d-db08b1b18b2f.png">

Is this not the case for you?

**Comment by bot1131357** [comment]
Thanks for the reply. Sorry I misread the diagram. The two other pieces where I've acquired from OSH Park works. I think the board I was testing on was faulty. Maybe I've damaged it somehow. I removed most of the components from the board, and yet 5V is still shorted to GND. Glad to get the other two pieces working though.
